# Generated by Django 2.0.1 on 2018-01-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
