# Generated by Django 2.0.1 on 2018-01-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20180121_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
